basic_features/basic_save_game_info.py

`os.path` is old and less safe than Pathlib, so I removed it while I wanted to meddle with this file anyway.
It looked suspicious that `getCreationTime` was returning the modification time instead of the creation time, so I changed that from `mtime` to `ctime`.
I also added handling for `value` being a `Path` object as that's the type for the thing it represents. I might not have needed the explicit `str` call as Path is implicitly convertible to `str` lots of the time, but I've not actually tested the change so wanted to play it safe.

Pathlib stuff

---

steam_utils.py

Apparently Steam is known to corrupt its own appmanifest
files.  This will make the plugin skip any outright unreadable
files.
This is flagged WIP as I have done zero testing.  Haven't even launched MO with this file yet.

Add robustness to reading Steam manifest files

---

steam_utils.py

Catch all exceptions instead of just a few and log the error. Fixes https://github.com/ModOrganizer2/modorganizer/issues/1425.

Errors with bad steam library paths

---

games/game_valkyriachronicles.py

I mostly just followed the instructions in the README.
While the DLCs have Steam IDs ([`314780`](https://steamdb.info/app/314780/), [`314781`](https://steamdb.info/app/314781/), [`314782`](https://steamdb.info/app/314782/) and [`314783`](https://steamdb.info/app/314783/)), I can't find any easy way of determining which folder corresponds to which DLC so MO2 currently doesn't list them in the mod list like it does for Skyrim. It'd be nice to get that working.
I didn't bother trying to parse anything from the save data - `playdata###.dat` starts with a mostly-ASCII string containing the date the save was made, the name of the chapter you're currently on, whether the save was made in book mode or campaign mode, and the time spent playing (three digits of hour, two digits of minute, padded …

Add basic Valkyria Chronicles support

---

games/game_valheim.py

Fix for bug ModOrganizer2/modorganizer#1677:
Checking for valid files in `ModDataChecker.fix` first to exclude them from being moved.
E.g. `winhttp.dll` is valid, has to stay in root dir, `*.dll` files have to be moved to `BepInEx/plugins`.

fix: Valheim Bepinex installation -  winhttp.dll

---

games/game_monsterhunterrise.py

Basic Monster Hunter: Rise support. Requires [FirstNatives](https://www.nexusmods.com/monsterhunterrise/mods/848) for mods to work.

Add Monster Hunter: Rise support

---

.gitignore
poetry.lock
pyproject.toml

- fixes psutil install error for python 11, see https://github.com/giampaolo/psutil/issues/2163#issuecomment-1307100407
- add .venv to gitignore + cleanup related linter exceptions

Fix python11 deps + linters

---

basic_features/basic_mod_data_checker.py

Fix for `valid` patterns not being accepted by `BasicModDataChecker.dataLooksValid()`, for more than one folder / file.
Affected games: Valheim, Subnautica (, Cyberpunk)

Fix valid match in `BasicModDataChecker.dataLooksValid()`

---

basic_game.py

Seems to be necessary even with UIBase implementing an empty default

Add enabledPlugins

---

README.md
basic_features/__init__.py
basic_features/basic_local_savegames.py
games/game_blackandwhite2.py
games/game_valheim.py
games/game_vampirebloodlines.py

Simplifies adding profile specific save games, by adding a default implementation of  `LocalSavegames`,
`BasicLocalSavegames`, to `basic_features`.
Refactors games using `LocalSavegames`, since they all use the same implementation anyways.
Added the class in a separate `basic_local_savegames`, would alternatively also fit into `basic_save_game_info`

Add BasicLocalSavegames (basic_feature)

---

README.md
basic_features/basic_save_game_info.py
basic_game.py
games/game_blackandwhite2.py
games/game_bladeandsorcery.py
games/game_subnautica.py

Adds optional metadata to the `BasicGameSaveGameInfoWidget`, similar to TES / Gamebryo games:
```py
BasicGameSaveGameInfo()  # Adds "File Date" by default
BasicGameSaveGameInfo(
get_preview = lambda p: Path(p, "screenshot.png"), # Save preview
get_metadata = lambda p, save: {"Name": save.getName(), ...}
)
```
Example from Cyberpunk 2077, included in #105:
Adds a default file date to all BasicGames, taken from the save game files (`GameSaveExtension` etc.)

Add metadata to BasicGameSaveGameInfo(Widget)

---

games/game_cyberpunk2077.py

Current state and workarounds (to be integrated) are described in the [wiki page for Cyberpunk 2077](/ModOrganizer2/modorganizer-basic_games/wiki/Game:-Cyberpunk-2077)
Implemented features in this plugin update
- ~Sync mod settings back to mods (some are currently saved to overwrite, since config files get created after game launch)~
Here is an overview of the mod / framework support as of MO 2.5 beta 14 (Cyberpunk game plugin v2.1) and the compatibility with MOs virtual file system USVFS:
<table>
<thead>
<tr>
<th colspan="2"></th>
<th colspan="2"> Support: mods&nbsp;/&nbsp;framework </th>
</tr>
<tr>
<th>Mod type / framework</th>
<th>Mod folder (files)</th>
<th>Auto install*</th>
<th>USVFS</th>
</tr>
</thead>
<tbody>
<tr>
<td>archive</td>
<td><code>archvie/...</code> …

Cyberpunk full support

---

games/game_cyberpunk2077.py

To be tested: [Cyberpunk plugin v2.2.2](https://github.com/ZashIn/modorganizer-basic_games/releases)
Fixes #105 issue ([comment](https://github.com/ModOrganizer2/modorganizer-basic_games/pull/105#issuecomment-1763463764))

Fix CyberpunkModDataChecker not accepting extra files

---

games/game_cyberpunk2077.py

Disable `enforce_archive_load_order` by default.
With the setting enabled, Mod Organizers load order is enforced for mods with `.archive` files. But most mod (authors) are expecting all `.archive` files to load in alphabetic order, with files in depended mods named accordingly.
Setting can be enabled for a manual archive conflict resolution via MOs load order.

Fix mods expecting alphabetical load order

---

README.md
basic_game.py

Just noticed that this is missing.
Makes it also possible to enable profile specific ini files from a `game_xy.ini` basic game config.
Same parsing as `GameValidShortNames`.
Could also replace all existing `iniFiles()` definitions with the property, to make it clear for others?

Add mapping `GameIniFiles`: `iniFiles()` to BasicGame

---

games/game_cyberpunk2077.py

Adds setting `clear_cache_after_game_update` (by default `True`) to clear cache automatically on game update, i.e. when the original game files change.
Details:
- with redscript: `r6/cache/final.redscript` is changed, `final.redscript.bk` is created as backup, which should always match the original game files
- with REDmod: file changes are written into subdir `/modded`, so `r6/cache/final.redscript` should match original game files
Therefore after a game update, `final.redscript` and `final.redscript.bk` (if exists) differ from original game files, so the plugin clears `r6/cache` and copies the new files to overwrite again.
Tested with Cyberpunk 2.01 -> 2.02

Cyberpunk fix game update

---

eadesktop_utils.py

ElementTree has a FutureWarning about not using the implicit truthiness test for an Element. So instead use the advertised test against `None` to silence the warning.

Fix ElementTree future warning

---

games/game_cyberpunk2077.py

Mod priority for redMod and `.archive` files has to be reversed compared to MOs priority.
MO:
1. modA
2. modB (higher priority)
should result in CP load order:
1. modB (higher priority)
2. modA
Applies only if the corresponding `enforce_XX_load_order` setting is enabled (by default for redMod), which generate
- `r6/cache/modded/MO_REDmod_load_order.txt`  (passed to `redmod.exe`)
- `archive/pc/mod/modlist.txt`
Otherwise mods are loaded in alphabetical order (CP default).

Fix Cyberpunk reversed mod priority for archive and redmod

---

games/game_subnautica-below-zero.py
games/game_subnautica.py

- Launch non VR version by default by adding `-vrmode none` to default exe
- Adds new exe: Subnautica VR (without the vrmode arg)
- Fixes Subnautica 2.0 (and BZ) mod installations (install `*/.dll` mods in `BepInEx/plugins` instead of `QMods`)
- Adds setting `use_qmods` to still use the legacy QMods folder (default=`False`)
TODO after merge:
- update wiki with the changed install method because of deprecated QMods, including the `use_qmods` setting
Edit: merged the fix for VR with the Subnautica 2.0 changes

Fix for Subnautica 2.0

---

games/game_cyberpunk2077.py

Fixes the following in MO 2.5+:
- remove debug return from #137. Sorry, slipped through testing. 
- set default for `skipStartScreen=False`, since it can also skip loading rewards, same as here e.g.: maximegmd/CyberEngineTweaks#663
- reverse the load order only optionally for better backwards compatibility (#132), add settings  `reverse_archive_load_order=False` and  `reverse_redmod_load_order=False` (see below)
Thx @ junki for the issue reports
The default load order settings are a compromise between default Cyberpunk / mod behavior (load mods alphabetically), backwards compatibility (load mods top to bottom = lower prio wins) and MOs known behavior from Skyrim etc. (highest prio mod wins).
Details about the load order as draft for the wiki:
With an example mod list
```
modB (priority 1) …
```

Cyberpunk fixes for 2.5

---

README.md
games/game_thps3.py
games/game_thps4.py
games/game_thug.py
games/game_thug2.py

Adds support for:
- Tony Hawk's Pro Skater 3
- Tony Hawk's Pro Skater 4
- Tony Hawk's Underground
- Tony Hawk's Underground 2
These games all run on a very similar engine but the ports are made by different porting studios so they work slightly different. Support is included for PARTYMOD for THPS3 & 4 and ClownJob'd for THUG1 & THUG2 which provide replacement game executables with several fixes for controller input, etc. THUG2 also supports THUGPRO, but THUGPRO modding is very limited.

Add Tony Hawk's Pro Skater 3, 4, Underground & Underground 2 Support

---

games/game_cyberpunk2077.py

Cyberpunk plugin update for MO 2.5.2

---

games/game_arkhamcity.py

Support for Batman: Arkham City. Ran a full modded playthrough using this plugin as I worked on it.

Add Batman: Arkham City support plugin

---

games/game_cyberpunk2077.py

Without this, modlist.txt ends up in the modlist, along with all the .xl files for ArchiveXL. While this doesn't seem to cause issues, it does confuse red4-conflicts a bit.

Cyberpunk: Only include .archive files from archive/pc/mod/

---

__init__.py

This should address an issue where basic game plugins are not loaded when the path to basic_games/games contains square brackets.

Use glob.escape for paths that contain square brackets

---

games/game_subnautica.py

Fixes error
```
[installerquick.cpp:168] unsupported archive for quick installer
```
Adds (common) workaround for `installerquick` traversing into single folder file tree even when plugin returns `FIXABLE` on root.
Also adds support for new files in [Tobey's BepInEx Pack for Subnautica v5.4.23](https://www.nexusmods.com/subnautica/mods/1108?tab=files)

Fix Subnautica installer error

---

games/game_finalfantasy7remake.py

In function `_active_mod_mappings`, `pak_priority_digits` was calculated based on log base 10 of number of mod paths for selected mods. When no mods are selected (or no paths present in selected mods), this takes log(0) resulting in a ValueError. But `pak_priority_digits` is not needed in this case, so this commit fixes by early exiting in case of no mod paths prior to computing `pak_priority_digits`.
Example crash:

Fix FF7 remake crash when no mods are selected

---

games/game_bladeandsorcery.py

Fixes errors in Blade & Sorcery when parsing saves. Didn't bothered with old saves because they are not supported by the game anymore.

Update Blade & Sorcery save parser to 1.0

---

games/game_cyberpunk2077.py

Remove RootBuilder support/requirement (for CET and RED4ext) in favor of forced load libraries:
CET and RED4ext will be installed normally via USVFS instead into `root` folder for RB.
Here is a [test release](https://github.com/ZashIn/modorganizer-basic_games/releases/tag/cyberpunk-v3.0b) for the current MO v2.5.2.
This needs to be tested on larger mod lists for stability!
Additional discussion: https://github.com/CDPR-Modding-Documentation/Cyberpunk-Modding-Docs/pull/37
Extras (in separate PR?):

Cyberpunk: forced load libraries instead of RB

---

README.md
epic_utils.py
games/game_control.py
games/game_cyberpunk2077.py
games/game_subnautica-below-zero.py

- Add detection of Epic Game Store games installed via [Heroic Games Launcher](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher).
- Fix detection for EGS installed games (synced in ProgramData)
- Add [Unofficial EGS ID DB](https://erri120.github.io/egs-db/) to the README
- Add EGS IDs to: Subnautica Below Zero, Cyberpunk, Control
Note: games with different savegame paths, like existing Subnatica support, would require an exposed API for correct path selection, e.g. via `.gameVariant()`

Add / extend game detection support for Epic Games (Heroic Games Launcher)

---

games/game_cyberpunk2077.py

Fixes an error (e.g. `Permission denied: ...r6\\cache\\modded`) when cleaning Cyberpunk script cache `r6/cache` with extra folder present in the game folder.
Normally `r6/cache` in a clean Cyberpunk installation should only contain `final.redscript` and `tweakdb.bin`.
This PR only fixes the file update logic (clean cache in overwrite and copy new files). Extra generated cache files in the game folder (before using MO) are still **NOT** handled and might get overwritten or deleted by the game / mods.
Although with a clean Cyberpunk installation, all generated (mod) cache files (while using MO) should be handled by this game plugin (in overwrite).
TODO for wiki:

Fix Cyberpunk r6/cache file updates

---

games/game_sims4.py

As far as I'm aware, this should be a pretty good validator/fixer for Sims 4 mods (that go in the Mods folder). Also added content detection support so I can see which mods EA keeps breaking (the scripts).

feat(sims4): add ModDataChecker, ModDataContent

---

basic_game.py
eadesktop_utils.py
epic_utils.py
games/game_sims4.py

- Catches errors while loading the game list (EA and Epic/Heroic/Legendary Games)
- Shows an error message at MO start with details about the problematic files and how to solve the problem
- Fixes lint errors (from #173 ?)
Remarks:
- I appended the original error message (without the stack trace), but one could also only log it and hide it from the message.
- This message will show up at every MO start until the files are either fixed or deleted. There is no option to hide it, since at this loading stage, there is no access to plugin options (`IOrganizer`)  or similar.
Example error message:
Extends #154

Catch and show game list errors at startup

---

games/game_valheim.py

Missing file in `ModDataChecker`: `.doorstop_version`

Valheim: fix BepInEx installation, missing file .doorstop_version
