basic_game.py
games/game_witcher3.py
games/game_zeusandposeidon.py
gog_utils.py
steam_utils.py

Features:
- GOG automatic detection, thanks to @erri120 and @EzioTheDeadPoet
- Support for multiple steam IDs and GOG IDs. 
- The game plugin should automatically use the right one (at least for `steamAPPId()`).
- Support for Zeus and Poseidon.

Add gog detection

---

basic_game.py
games/game_stalkeranomaly.py

Rename mappings to avoid collision

---

games/game_kingdomcomedeliverance.py

Uploaded the incorrect file by accident. New file has the proper changes.

Fix spelling and syntax on game_kingdomcomedeliverance.py

---

README.md
games/game_darkestdungeon.py
games/game_dungeonsiege2.py

Revisions to some game plugins to incorporate GOG Id's. Additional corrections, quality of life edits and visual updates to the README.md file.

Various Updates to game plugins and README.md file

---

.gitignore
README.md
games/game_darkestdungeon.py
steam_utils.py

- Fixes the working directory for the DD executable
- Save Location Detection
- Save Slot display

Darkest Dungeon fixes

---

CMakeLists.txt
steam_utils.py

Closes ModOrganizer2/modorganizer#1422

Fix appmanifest backup.

---

games/game_darkestdungeon.py

@Holt59 looks like you forgot to rename this one

Fix missing isSteam function for DD

---

games/game_nomanssky.py

Fixed typo in ID for GameNexusName.
Added GameNexusId.

Minor edits to basic game def for No Man's Sky

---

README.md
basic_game.py
games/game_divinityoriginalsin.py
games/game_divinityoriginalsinee.py

This includes the original (untested, mostly just for Nexus
download support) and the enhanced edition (actually somewhat
tested).
~~This is some basic support for mods installed in the game
folder.  There's also a location for actual packaged mods
in the Documents folder that I hope to add support for at
some point.~~

Add support for Divinity Original Sin

---

games/game_starsector.py

- Cleaned the list save part of the Starsector script

Cleaned Starsector script

---

games/game_kerbalspaceprogram.py

Added save game awareness, including support for preview images, if available (i.e. scenarios, mostly).

Add basic save preview support

---

steam_utils.py

See [here](https://github.com/erri120/gamefinder#steam) for more info on the formats.

Fix libraryfolders.vdf format detection

---

games/game_daggerfallunity.py

This adds support for Daggerfall Unity.  It has rudimentary support for determining if a mod is packaged correctly.

Add support for Daggerfall Unity.

---

steam_utils.py

Fix for libraryfolders.vdf containing utf-8 encoding

Add support for utf-8

---

games/game_blackandwhite2.py

BW2 minor patch 

---

games/game_subnautica.py

This will add basic support for Subnautica. I have only tested it with the Steam version, but I guess the Epic Store version should work too.

Add support for Subnautica

---

games/game_subnautica-below-zero.py

This will add basic support for Subnautica: Below Zero. Like in #64 I have only tested it with the Steam version, but I guess the Epic Store version should work too.

Add support for Subnautica: Below Zero

---

games/game_stalkeranomaly.py

Improved ModDataChecker and added ModDataContent

STALKER Anomaly: Add ModDataContent

---

games/game_subnautica.py

Fix a typo in the Subnautica plugin

Fix subnautica typo

---

games/game_subnautica-below-zero.py
games/game_subnautica.py

Fix a typo in the Subnautica: Below Zero plugin

Fix subnautica below zero typo

---

README.md
games/game_masterduel.py

Adding the plugin and editing the readme appropriately to add Master Duel to the listing.

Add Yu-Gi-Oh! Master Duel

---

games/game_trainsimulator.py

Data and executables only; pretty basic stuff. Train Simulator has save states, but they are only used to save/resume individual sessions, so I doubt anyone would be interested in managing them. As for DLC, the game has so much of it (it's a running joke) that it would be fruitless to try to track every single Steam ID.

Add basic Train Simulator support

---

games/game_blackandwhite2.py
games/game_masterduel.py
games/game_valkyriachronicles.py

This is theoretically a non-functional change

Make linters happy

---

games/game_valheim.py

Fixed:
- Added file patterns to cover Jotunn (mod library) installation: .dll.mdb, .pdb, .xml
Changes based on #90 (definitions based on `BasicModDataChecker`).
Tested with MO v2.5.0 Alpha 3

Valheim: fix overwrite sync, Jotunn install

---

games/game_blackandwhite2.py

BlackAndWhite2Game inheriting from mobase.IPluginFileMapper prevent launching the game because mappings is called and is a pure virtual function (not implemented by the plugin).
Not remembering why i did it and not seeing any purpose for this choice i removed this inheritance and it works again.
I took advantage of this time to redo the GameInfo panel using the getMetadata instead of doing my own preview window

Fixes for Black & White 2 plugins

---

games/game_cyberpunk2077.py

cache file paths were not relative...

Fix cyberpunk cache file sync after game update

---

games/game_f123.py

Needed for my future mod on NexusMods

F1 23 plugin

---

games/game_witcher2.py

Add The Witcher 2 support.

---

basic_features/basic_mod_data_checker.py
games/game_valheim.py

- Fix for [Jotunn ](https://www.nexusmods.com/valheim/mods/1138) install.
- Fix Bepinex install: changelog.txt was added
Requires changes from #142, too.

Fixes for Valheim

---

games/game_valheim.py

Fix Valheim: Add Translations folder to ModDataChecker

---

games/game_readyornot.py

Include basic support for Ready or Not
Note: Some features are not available
- Cannot recognize mod archive contents
- Cannot set loading priority ( dont know how to implement this )
- No metadata for mods

Feat: Add Ready or Not support

---

games/game_x4.py

For a long awhile an X4 Foundations support plugin has been passed around on Reddit and Discord, with how basic of a game it is to mod and how straightforward the plugin actually is, I think it should be added into the base MO community plugins
- Add `game_x4.py`, a supporting plugin for the game [X4: Foundations](https://store.steampowered.com/app/392160/X4_Foundations/) and it's [Nexus Mods listing](https://www.nexusmods.com/x4foundations)

Add X4: Foundations supporting plugin

---

basic_game.py

Fix BasicGames.is_gog(): setGamePath() is not setting gogAPPId

---

games/game_silksong.py

Added basic suport for silksong, including beaing able to download directly from nexus

Add silksong suport 
